import { Geist, Geist_Mono, Poppins } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";
import Navbar from "@/components/layouts/Navbar";
import Footer from "@/components/layouts/Footer";

const poppins = Poppins({
  weight: ["100", "200", "400", "500", "600", "800"]
})

export const BanglaFont = localFont({
  src: '../fonts/mayaboti-normal.ttf',
})

export const metadata = {
  title: "Hero Kidz",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
    >
      <body className={`${poppins.className} h-full antialiased min-h-full flex flex-col`}>
        <header className="h-[49.41px]">
          <Navbar></Navbar>
        </header>
        <main className="2xl:w-11/12 w-full mx-auto min-h-[calc(100vh-302px)]">
          {children}
        </main>
        <footer>
          <Footer></Footer>
        </footer>
      </body>
    </html>
  );
}